#: kivy 1.11.1

<YouScrolled>:
    Label:
        font_size: 90
        center_x: root.width / 2
        top: root.top-100
        text: "Wow! You've \ntravelled:"

    Label:
        font_size: 100
        center_x : root.width/2
        top : root.top*0.4
        text : str(round(root.total_distance, 2))
    Label:
        font_size: 60
        center_x : root.width/2
        top : root.top*0.2
        text : "Pixels..don't tire yourself now."
    
        